kiss-initpkg: add version and source from the script itself.

diff --git a/contrib/kiss-initpkg b/contrib/kiss-initpkg
--- a/contrib/kiss-initpkg
+++ b/contrib/kiss-initpkg
@@ -1,11 +1,23 @@
 #!/bin/sh -e
 
-[ -z "$1" ] && exit 1
-for dir in "$@" ; do
-	mkdir -p "$dir"
-	for file in version sources build; do
-		:> "$dir/$file"
-	done
-	chmod +x "$dir/build"
-	printf "\033[1;33m->\033[0;00m Added empty package \033[1;36m$dir\033[0;00m to $PWD/$dir\n"
-done
+out() { printf "=> $1\n" ;}
+die() { printf "error: $1\n" ; exit 1 ;}
+[ -z "$1" ] && { out "${0##*/} <package> [version] [sources]"; exit ;}
+[ -d "$1" ] && die "Package $1 already exists"
+
+mkdir -p "$1" || die "Couldn't create directory in $PWD"
+
+out "Populating build file" ; {
+printf "#!/bin/sh -e\n" > "$1/build"
+chmod +x "$1/build"
+}
+
+[ -n "$2" ] && {
+	out "Populating version file with '${2%% *} 1'"
+	printf "${2%% *} 1\n" > "$1/version"
+} || :> "$1/version"
+
+[ -n "$3" ] && {
+	out "Populating sources file with '$3'"
+	printf "$3\n" > "$1/sources"
+} || :> "$1/version"
