kiss: support a system-wide hook directory with easy use.
Hooks installed to /var/db/kiss/hooks can be accessed via their
basename. Usage is as follows.

$ ls -1 /var/db/kiss/hooks
no-docs
shell-on-exit

$ export KISS_HOOK=no-docs:shell-on-exit:/home/dylan/bin/kiss_hook

See #229

diff --git a/kiss b/kiss
--- a/kiss
+++ b/kiss
@@ -120,9 +120,18 @@ run_hook() {
 
     unset IFS
 
-    for hook do "$hook" "$_type" "$_name" "$_path" ||
-        die "$_name" "$_type hook failed: '$hook'"
-    done
+    for hook do case $hook in
+        */*)
+            # Absolute path to hook.
+            "$hook" "$_type" "$_name" "$_path"
+        ;;
+
+        *)
+            # Hook in system-wide hook directory (/var/db/kiss/hooks).
+            # Hooks in this directory can be used via their basename.
+            "$sys_db/../hooks/$hook" "$_type" "$_name" "$_path"
+        ;;
+    esac || die "$_name" "$_type hook failed: '$hook'"; done
 }
 
 run_hook_pkg() {
