kiss-new: Polish

diff --git a/kiss b/kiss
--- a/kiss
+++ b/kiss
@@ -41,9 +41,10 @@ pkg_lint() {
 
     cd "$pkg_location" || die "'$pkg_location' not accessible"
 
-    [ -f sources ]  || die "Sources file not found."
-    [ -x build ]    || die "Build file not found or not executable."
-    [ -s version ]  || die "Version file not found or empty."
+    [ -f sources ]   || die "[$1]: Sources file not found."
+    [ -x build ]     || die "[$1]: Build file not found or not executable."
+    [ -s version ]   || die "[$1]: Version file not found or empty."
+    [ -f checksums ] || die "[$1]: Checksums file not found."
 
     # Ensure that the release field in the version file is set
     # to something.
@@ -410,27 +411,6 @@ pkg_build() {
     done
 
     for pkg; do pkg_lint "$pkg"; done
-    for pkg; do
-        # Find the package's repository files. This needs to keep
-        # happening as we can't store this data in any kind of data
-        # structure.
-        repo_dir=$(pkg_search "$pkg")
-
-        # Ensure that checksums exist prior to building the package.
-        [ -f "$repo_dir/checksums" ] || {
-            log "[$pkg]: Checksums are missing."
-
-            # Instead of dying above, log it to the terminal. Also define a
-            # variable so we *can* die after all checksum files have been
-            # checked.
-            no_checkums="$no_checkums$pkg "
-        }
-    done
-
-    # Die here as packages without checksums were found above.
-    [ "$no_checkums" ] &&
-        die "Run '$kiss checksum ${no_checkums% }' to generate checksums."
-
     for pkg; do pkg_sources "$pkg"; done
     for pkg; do pkg_verify  "$pkg"; done
 
